### ISSUE TITLE
Insufficient Permissions Error

### ISSUE THREAD

**Issue by manikandancode** [lo2dev/Echo#3]
OS: Ubuntu 24.04 Wayland

![Screenshot from 2024-07-05 11-20-34](https://github.com/lo2dev/Echo/assets/46480489/f63d02dc-9cba-487e-9075-90477b6d539d)

![Screenshot from 2024-07-05 11-20-19](https://github.com/lo2dev/Echo/assets/46480489/250b5b61-4da7-4ecb-b12c-3844f8562307)

**Comment by lo2dev** [comment]
Refer to https://github.com/lo2dev/Echo#insufficient-permissions
